apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pazuu-read
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pazuu-read
  template:
    metadata:
      labels:
        app: pazuu-read
    spec:
      containers:
      - name: pazuu-read
        image: nnao45/pazuu
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          successThreshold: 1
          periodSeconds: 3
          initialDelaySeconds: 15
          successThreshold: 1
          failureThreshold: 1
          timeoutSeconds: 1
        ports:
        - name: http
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pazuu-read
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pazuu-read
  type: LoadBalancer
